### ISSUE TITLE
Mobile Meta Tag

### ISSUE THREAD

**Issue by Mikeysax** [KyleDuca/splurty#1]
On mobile things don't look as good as they could be.
One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.
Let me know in the comments once you figured that step out :)

**Comment by KyleDuca** [comment]
Aright, I fixed it and it seems good now!
https://splurty-kyle-duca.herokuapp.com/

The only thing that keeps throwing me for a loop is the process of updating github. I updated and did $ git add --all  and $ git commit -am "comment" , but It's not showing up.

Regardless, it seems to be working well on heroku, so I'll just ask my mentor when the time comes about it.

Thanks!

**Comment by Mikeysax** [comment]
Nice! Good job figuring out the mobile meta tag 👍
